- src/App.js
- src/components/Form.jsx
- src/views/CreatePost.jsx
Arreglo rutas, creo componente FormSingUp y arreglo pequeños errores en otros componentes
> Routes fix, component FormSingUp

- src/views/Landing.jsx
Creando nuevamente Landing con Mayuscula!
> Landing fix

- src/App.js
- src/components/Login.jsx
- src/components/Login/Login.jsx
- src/components/Login/validateLogin.js
- src/components/SignUp/FormSingUp.jsx
- src/index.js
- src/views/Landing.jsx
- src/views/Profile.jsx
> componentes, app, index, validations

- public/index.html
- src/App.js
- src/components/NavBar.jsx
- src/components/Posts.jsx
- src/components/SideBar.jsx
- src/views/Home.jsx
Hardcodee el Post para los estilos de tailwind
> styles, posts harcoded

- src/App.js
- src/redux/actions.js
- src/redux/reducer.js
- src/views/Profile.jsx
Arreglo la ruta de profile para que nos muestre el  username y no el id
> fix profile route

- src/components/Post.jsx
- src/components/Posts.jsx
- src/views/CreatePost/CreatePost.jsx
- src/views/Profile.jsx
intente traer cosas del back, como no pude tuve que hardcodear para los estilos, ya no debería dar problemas
> fix de estilos y hardcodeo

- src/redux/actions.js
- src/redux/reducer.js
- src/views/CreatePost/CreatePost.jsx
Agrego action de Post de posteos, cambios en CreatePost
> completo createPost

- src/views/CreatePost/createPostValidation.js
> postValidation

- src/components/SearchBar.jsx
- src/components/SideBar.jsx
- src/redux/actions.js
- src/redux/reducer.js
- src/redux/types.js
Subo SearchBar como componente, creamos los types correspondientes para las actions de la búsqueda. Cambios correspondientes en reducer. Saludos a Lucas.
> Creación SearchBar y types, actions, reducer

- src/components/Post.jsx
- src/components/PostDetail.jsx
Agregamos fecha y hora que viene del back a los componentes Post y DetailPost
> Trayendo fecha y hora del back

- src/components/Search/SearchBar.jsx
Incluimos el borrar input en la SearchBar
> Se borra la busqueda al buscar

- src/components/Login/Login.jsx
- src/components/SignUp/FormSingUp.jsx
- src/views/Detail.jsx
- src/views/Profile.jsx
Cambios para el post de nuevo usuario y Log in
> Login, FormSingUp, Detail, Profile

- src/App.js
- src/components/NavBar.jsx
- src/views/Home.jsx
- src/views/Payment.jsx
Creé la ruta correspondiente en App.
Creé un botón para hacerte Premium en nuestra NavBar.
Saqué el Wallet de Home y creé el componente Payment para visualizarlo donde se necesite.
> Creo el componente Payment

- package-lock.json
- package.json
- src/firebase/config.js
- src/views/CreatePost/CreatePost.jsx
- src/views/CreatePost/createPostValidation.js
Instalo firebase (hacer npm install). Sólo se puede subir 1 archivo en el form por ahora.
> CreatePost, se puede subir 1 archivo

- src/components/Login/Login.jsx
- src/components/PostDetail.jsx
- src/firebase/config.js
- src/views/CreatePost/CreatePost.jsx
Subir varios archvios en CreatePost (falta un fix)
Agrego ver imagenes en PostDetail
Fix en Login
> CreatePost,  PostDetail, Login

- src/views/CreatePost/CreatePost.jsx
- src/views/CreatePost/createPostValidation.js
Fixea el funcionamiento de subir una o mas imagenes y se guardan en la base de datos y en la nube de Firebase
> fix CreatePost

- src/views/About.jsx
Agrego el botón en About para volver a Landing
> Boton a Landing

- src/views/About.jsx
- src/views/Landing.jsx
Estilos del botón para ir a About
Varios cambios en About
> Landing, About

- src/views/Profile.jsx
Reformulo la logica de los renderizados condicionales para los bugs de la imagen de perfil
> Fix Profile

- package.json
comando de inicio actual "npm run dev"
> npm run dev ejecuta tailwind y react

- src/App.js
- src/views/Profile.jsx
Arreglo todas las vistas del NotFound, faltan estilos!!!
> Fix NotFound

- src/views/Profile.jsx
> Link en Profile

- src/components/Trash.jsx
le agrego el window.location.reload() en Trash asi se elimina y actualiza la pagina al borrar el post
> Reload en Trash
